project:
  type: website
  output-dir: docs

website:
  title: "M'Power Gift Planner"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar: 
    style: "docked"
    logo: images/logo.png


format:
  html:
    theme: cerulean
    css: styles.css
    toc: false



