project:
  type: website
  output-dir: docs

website:
  title: "M'Power Gift Planner"
  search: false
  navbar:
    tools:
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=61553658621684
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Who We Are

  sidebar: 
    style: "docked"
    logo: images/logo.png


format:
  html:
    theme: simplex
    css: styles.css
    toc: false



