---
title: "Plan Your Gift!"
---

## The Good Giving Challenge:  How It Works

During the course of the Giving Challenge there are certain periods of time during which your gift can be matched by a donor fund.

The funds (described in an [Appendix](#appendix) below)  differ in how much they will match, in the upper limit on how much they will match any gift, and in their total "pool" of money available to match gifts.

Given the differences between the funds, you are probably wondering:

>*How and when should I give so as to maximize the amount that M'Power Rhythm receives?*

This site aims to help you with your question!

## Our Recommendations

Depending on the amount you are giving it may be best to split the gift and give it over multiple days to maximize the matching funds.

We can help you schedule your gift! Just enter your total gift below. (**Note**: Our recommendations will update automatically.) 

```{=html}
<input id="optimize-input" type="number" value="1000" min="10" step = "10">
<br>
<br>
<p id="we-get"></p>
```

```{=html}
<div id="optimize-output"></div>
```

::: {.callout-caution}
## Good Advice

Within each time-window, try to give as early as possible, before the fund's matching-pool is exceeded!
:::

```{=html}
<a class="btn btn-outline-primary" href="https://www.bggives.org/organization/MPower_Rhythm" role="button">Donate Now</a>
```

## Do-It-Yourself Option

You might have a special interest in engaging with some of the funds or prefer to give on particular days.  If you are still interested in maximizing the money we get from your gift---the recommendation we provided in the previous section is usually not a unique solution---then we offer the following advice:

* If you are a small-to-moderate donor, you'll probably be able to generate the maximum gift to us by making just one donation:
    * Look for a time-window with the highest matching-rate (e.g., $1 for every dollar given is better than $0.50 for every dollar given).
    * Look also for high maximum matches.  For example, suppose you plan to give $150 and you have a choice between two funds, both of which match at the same rate but Fund A does not match gift amounts $100 whereas fund B matches gift amounts up to $200, then you'll generate more money for us by working with Fund B.)
* If you are a "heavy-hitter", then you should consider splitting your gift over several time-windows in order to leverage multiple matching opportunities.  

::: {.callout-tip collapse="true"}

## Want More Help? Expand to use our interactive table!

```{=html}
<table id="diy" class="table table-bordered table-hover">

</table>
```
:::

```{=html}
<a class="btn btn-outline-primary" href="https://www.bggives.org/organization/MPower_Rhythm" role="button">Donate Now</a>
```



## Appendix

Here are the matching funds:

```{=html}
<ul id="matchers">

</ul>
```

```{=html}
<script src="js/main.js"></script>
```


